-- AlterTable
ALTER TABLE `leavecode` ADD COLUMN `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `days` INTEGER NULL,
    ADD COLUMN `finYearId` INTEGER NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NULL,
    MODIFY `name` VARCHAR(191) NULL,
    MODIFY `code` VARCHAR(191) NULL;

-- AddForeignKey
ALTER TABLE `LeaveCode` ADD CONSTRAINT `LeaveCode_finYearId_fkey` FOREIGN KEY (`finYearId`) REFERENCES `FinYear`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
